CREATE TABLE IF NOT EXISTS prices (
    name VARCHAR(255) PRIMARY KEY,
    last_24h DECIMAL(10,2) NULL,
    last_7d DECIMAL(10,2) NULL,
    last_30d DECIMAL(10,2) NULL,
    last_90d DECIMAL(10,2) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_prices_name ON prices(name);
